db:
    image: sameersbn/postgresql:9.4
    environment:
        - DB_NAME
        - DB_USER
        - DB_PASS
    ports:
        - "5432"
    volumes:
        - ./docker-vol/postgresql:/var/lib/postgresql

web:
    build: .
    volumes:
        - ./docker-vol:/opt/localshop
    links:
        - db:db
    environment:
        - DJANGO_SECRET_KEY
        - DATABASE_URL
        - DJANGO_MEDIA_ROOT
    ports:
        - "8000:8000"
    command: uwsgi --http 0.0.0.0:8000 --module localshop.wsgi --master --die-on-term


worker:
    build: .
    volumes:
        - ./docker-vol:/opt/localshop
    links:
        - db:db
    environment:
        - DJANGO_SECRET_KEY
        - DATABASE_URL
        - DJANGO_MEDIA_ROOT
    entrypoint:
        localshop
    command:
        celery worker -B -E
